### ISSUE TITLE
[Question] Adding a second UE

### ISSUE THREAD

**Issue by GinesGarcia** [pgorczak/srslte-docker-emulated#1]
Hi!
I would like to add a second UE to this scenario but I'm still learning how docker stuff works in detail. What I'm trying to do is to add this command "cat srsue/ue.conf.fauxrf.example | sed -e "s/imsi = 001010123456789/imsi = 001010123456780/" > srsue/ue.conf2.fauxrf.example" to the Dockerfile in order to have a configuration file for the second UE. Moreover, I've added the following in the docker-composed file:

  ```
srsue2:
    container_name: virtual-srsue2
    build: .
    command: "srsue ue.conf2.fauxrf"
    ipc: "container:virtual-srsenb"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    depends_on:
      - srsenb
```

With this configuration, "srsue2" is not working ( missing configuration file). How can I solve this problem?

Thanks in advance,
Ginés.
