### ISSUE TITLE
Transit from docker to k8s

### ISSUE THREAD

**Issue by Cindia-blue** [pgorczak/srslte-docker-emulated#2]
When I use k8s to deploy epc, I got below error with the same image, could you share hints about that?

Reading configuration file epc.conf...
HSS Initialized.
MME GTP-C Initialized
MME Initialized.
Could not initialize the SGi interface.
Error initializing SP-GW

**Comment by Cindia-blue** [comment]
how to translate the devices through h8s yml

devices:
    - /dev/net/tun

**Comment by pgorczak** [comment]
I know almost nothing about k8s but I found an [example](https://caveofcode.com/2017/06/how-to-setup-a-vpn-connection-from-inside-a-pod-in-kubernetes/) on how to make sure the /dev/net/tun special file exists within the pod (although for use with OpenVPN).

Tl;dr they added a startup script containing this

    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200
    chmod 600 /dev/net/tun

Can you make it work like this?

**Comment by rafis** [comment]
Translating this to k8s language you need to add the following to your deployment manifest:
```
        volumeMounts:
        - mountPath: /dev/net/tun
          name: dev-tun
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_NICE
      volumes:
      - hostPath:
          path: /dev/net/tun
          type: CharDevice
        name: dev-tun
```
